version: "3.9"
   
services:
  websocket:
    build: ./websocket/.
    ports:
      - "4000:4000"
      - "8000:8000"

  web:
    build: ./app/.
    ports:
      - "3000:3000"
    depends_on:
      - websocket

